[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configuration des formulaires Netlify
[forms]
  # Configuration pour recevoir les notifications par email
  [forms.settings]
    # Email de notification pour tous les formulaires
    notification_email = "robin@glp1-france.fr"

# Notifications pour le formulaire de contact
[[forms]]
  name = "contact"
  notification_email = "robin@glp1-france.fr"
  subject = "🆕 Nouveau message de contact - GLP-1 France"

# Notifications pour la newsletter
[[forms]]
  name = "newsletter" 
  notification_email = "robin@glp1-france.fr"
  subject = "📧 Nouvelle inscription newsletter - GLP-1 France"

# Notifications pour le guide beauté
[[forms]]
  name = "beauty-guide"
  notification_email = "robin@glp1-france.fr"
  subject = "📖 Nouveau téléchargement Guide Beauté - GLP-1 France"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Gestion des erreurs 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
