#!/usr/bin/env node
'use strict';
const https = require('https');
const SUPA_HOST = 'ywekaivgjzsmdocchvum.supabase.co';
const SUPA_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3ZWthaXZnanpzbWRvY2NodnVtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTM2NDQwNywiZXhwIjoyMDcwOTQwNDA3fQ.ryMev0CT2nnLWLG-5dtEeUEvWysi1dsa2e2yoq3w7Fs';
function apiRequest(method, path, body) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const opts = { hostname: SUPA_HOST, path: path, method: method, headers: { 'apikey': SUPA_KEY, 'Authorization': 'Bearer ' + SUPA_KEY, 'Content-Type': 'application/json', 'Prefer': 'return=representation' } };
    if (data) opts.headers['Content-Length'] = Buffer.byteLength(data);
    const req = https.request(opts, (res) => { let d = ''; res.on('data', chunk => d += chunk); res.on('end', () => { try { resolve({ status: res.statusCode, body: JSON.parse(d) }); } catch { resolve({ status: res.statusCode, body: d }); } }); });
    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}
const OPPORTUNITIES = [
  { topic: 'Effets secondaires Mounjaro (tirzepatide) : guide complet et gestion semaine par semaine', description: 'Mounjaro est le GLP-1 le plus prescrit en France 2025-2026 mais aucun article ne couvre ses effets secondaires specifiques. Nausees (44%), vomissements, diarrhees, pancreatite, signal thyroide EMA, reactions site injection.', target_keyword: 'effets secondaires Mounjaro tirzepatide', estimated_volume: 'high', competition: 'medium', priority: 1, suggested_collection: 'effets-secondaires-glp1', suggested_slug: 'effets-secondaires-mounjaro-tirzepatide-guide-complet', source_urls: ['https://www.ema.europa.eu/en/medicines/human/EPAR/mounjaro', 'https://ansm.sante.fr'], competitor_urls: ['https://www.doctissimo.fr/medicaments/mounjaro', 'https://www.vidal.fr/medicaments/gammes/mounjaro'] },
  { topic: 'Combien de temps prend un GLP-1 pour faire effet ? Timeline semaine par semaine', description: 'Question la plus posee par les nouveaux patients. Guide pratique avec timeline : semaines 1-4 adaptation, semaines 4-12 premieres pertes, mois 3-6 acceleration, mois 6-12 plateau. Format ideal pour SEO longue traine.', target_keyword: 'combien de temps effet GLP-1 Ozempic semaine resultats', estimated_volume: 'high', competition: 'medium', priority: 2, suggested_collection: 'glp1-perte-de-poids', suggested_slug: 'combien-temps-effet-glp1-ozempic-wegovy-resultats-semaine-par-semaine', source_urls: ['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9271646/', 'https://www.has-sante.fr'], competitor_urls: ['https://www.doctissimo.fr', 'https://www.sante-magazine.fr', 'https://www.passeportsante.net'] },
  { topic: 'GLP-1 et steatose hepatique NASH/NAFLD : resultats cliniques et espoirs 2025', description: 'La steatose hepatique touche 25% des adultes obeses en France. Essai ESSENCE (semaglutide) montre reduction significative steatose et fibrose. Sujet emergent 2025, aucun article sur le site.', target_keyword: 'GLP-1 foie steatose hepatique NASH traitement', estimated_volume: 'medium', competition: 'low', priority: 3, suggested_collection: 'recherche-glp1', suggested_slug: 'glp1-steatose-hepatique-nash-nafld-semaglutide-resultats-2025', source_urls: ['https://www.nejm.org', 'https://www.snfge.org'], competitor_urls: ['https://www.passeportsante.net', 'https://www.vidal.fr'] },
  { topic: 'Guide complet Rybelsus (semaglutide oral comprime) : utilisation, efficacite et avis patient', description: 'Il existe un article prix-rybelsus mais pas de guide complet patient : regles de prise strictes, dosages 3/7/14mg, effets secondaires, efficacite vs injectable, remboursement SS.', target_keyword: 'Rybelsus semaglutide oral comprime guide avis efficacite', estimated_volume: 'high', competition: 'medium', priority: 4, suggested_collection: 'traitements-glp1', suggested_slug: 'rybelsus-semaglutide-oral-guide-complet-utilisation-efficacite-avis', source_urls: ['https://www.ema.europa.eu/en/medicines/human/EPAR/rybelsus', 'https://www.ameli.fr'], competitor_urls: ['https://www.vidal.fr/medicaments/gammes/rybelsus', 'https://www.doctissimo.fr'] },
  { topic: 'GLP-1 et prevention cardiovasculaire : essai SELECT, infarctus et AVC — resultats France', description: 'L\'essai SELECT (semaglutide, -20% evenements cardiovasculaires chez non-diabetiques obeses) a transforme les GLP-1 en medicaments de prevention cardio.', target_keyword: 'GLP-1 prevention cardiovasculaire infarctus AVC essai SELECT', estimated_volume: 'medium', competition: 'low', priority: 5, suggested_collection: 'recherche-glp1', suggested_slug: 'glp1-prevention-cardiovasculaire-infarctus-avc-essai-select-france-2026', source_urls: ['https://www.nejm.org/doi/full/10.1056/NEJMoa2307563', 'https://www.sfcardio.fr'], competitor_urls: ['https://www.passeportsante.net', 'https://www.vidal.fr'] },
  { topic: 'Zepbound vs Mounjaro : meme molecule tirzepatide, deux indications France', description: 'Beaucoup confondent Zepbound (tirzepatide obesite, AMM EMA 2024) et Mounjaro (tirzepatide diabete type 2). Article comparatif differences legales, remboursement SS, disponibilite pharmacie.', target_keyword: 'Zepbound vs Mounjaro difference France tirzepatide', estimated_volume: 'medium', competition: 'low', priority: 6, suggested_collection: 'traitements-glp1', suggested_slug: 'zepbound-vs-mounjaro-difference-obesite-diabete-tirzepatide-france', source_urls: ['https://www.ema.europa.eu/en/medicines/human/EPAR/zepbound', 'https://ansm.sante.fr'], competitor_urls: ['https://www.vidal.fr', 'https://www.doctissimo.fr'] },
  { topic: 'Comment arreter Ozempic ou Mounjaro : protocole de sevrage progressif et transition', description: 'Distinct de l\'article arret-glp1-reprise-poids : focus sur le COMMENT arreter — reduction progressive doses, suivi glycemique diabetiques, transition vers autre traitement.', target_keyword: 'comment arreter Ozempic Mounjaro sevrage progressif protocole', estimated_volume: 'high', competition: 'low', priority: 7, suggested_collection: 'traitements-glp1', suggested_slug: 'comment-arreter-ozempic-mounjaro-protocole-sevrage-progressif-transition', source_urls: ['https://www.has-sante.fr', 'https://ansm.sante.fr'], competitor_urls: ['https://www.sante-magazine.fr', 'https://www.doctissimo.fr'] },
  { topic: 'GLP-1 et troubles du comportement alimentaire : boulimie et hyperphagie — donnees 2025', description: 'Les GLP-1 agissent sur les circuits de recompense cerebraux et reduisent les compulsions. Etudes 2024-2025 sur binge eating. Sujet distinct de l\'accompagnement psychologique existant.', target_keyword: 'GLP-1 troubles comportement alimentaire boulimie hyperphagie binge eating', estimated_volume: 'medium', competition: 'low', priority: 8, suggested_collection: 'recherche-glp1', suggested_slug: 'glp1-troubles-comportement-alimentaire-boulimie-hyperphagie-tca-etudes-2025', source_urls: ['https://www.ncbi.nlm.nih.gov', 'https://www.ffab.fr'], competitor_urls: ['https://www.passeportsante.net', 'https://www.doctissimo.fr'] },
  { topic: 'Temoignage : Wegovy apres chirurgie bariatrique inefficace — transformation reelle', description: 'Temoignage d\'une patiente sleeve gastrectomie + reprise poids puis Wegovy. Profil representatif 70 000 operes bariatriques/an France.', target_keyword: 'temoignage Wegovy apres chirurgie bariatrique sleeve reprise poids', estimated_volume: 'medium', competition: 'low', priority: 9, suggested_collection: 'temoignages', suggested_slug: 'temoignage-femme-wegovy-apres-chirurgie-bariatrique-sleeve-reprise-poids', source_urls: [], competitor_urls: ['https://www.doctissimo.fr', 'https://www.sante-magazine.fr'] },
  { topic: 'GLP-1 et Alzheimer / declin cognitif : premieres preuves et essai EVOKE 2026', description: 'Des etudes 2023-2025 suggerent que le semaglutide reduit le risque de demence. L\'essai EVOKE est en cours. Sujet tres mediatise 2025, aucun article sur le site.', target_keyword: 'GLP-1 Alzheimer demence declin cognitif semaglutide etude', estimated_volume: 'medium', competition: 'low', priority: 10, suggested_collection: 'recherche-glp1', suggested_slug: 'glp1-alzheimer-demence-declin-cognitif-semaglutide-etude-evoke-2026', source_urls: ['https://www.alzheimer-europe.org', 'https://www.ncbi.nlm.nih.gov'], competitor_urls: ['https://www.passeportsante.net', 'https://www.doctissimo.fr'] }
];
async function main() {
  console.log('=== Agent Opportunites GLP1 France ===');
  const runRes = await apiRequest('POST', '/rest/v1/agent_runs', { agent_name: 'opportunities', status: 'started' });
  if (runRes.status !== 201) { console.error('Erreur run:', runRes.status, JSON.stringify(runRes.body)); process.exit(1); }
  const runId = Array.isArray(runRes.body) ? runRes.body[0].id : runRes.body.id;
  console.log('Run ID:', runId);
  let inserted = 0, skipped = 0, errors = 0;
  for (const opp of OPPORTUNITIES) {
    const chkRes = await apiRequest('GET', '/rest/v1/content_opportunities?target_keyword=eq.' + encodeURIComponent(opp.target_keyword) + '&status=neq.rejected&select=id');
    const existing = Array.isArray(chkRes.body) ? chkRes.body : [];
    if (existing.length > 0) { console.log('[SKIP] P' + opp.priority, opp.target_keyword.substring(0, 50)); skipped++; continue; }
    const insRes = await apiRequest('POST', '/rest/v1/content_opportunities', { agent_run_id: runId, topic: opp.topic, description: opp.description, target_keyword: opp.target_keyword, estimated_volume: opp.estimated_volume, competition: opp.competition, priority: opp.priority, suggested_collection: opp.suggested_collection, suggested_slug: opp.suggested_slug, source_urls: opp.source_urls, competitor_urls: opp.competitor_urls, status: 'approved' });
    if (insRes.status === 201) { console.log('[OK] P' + opp.priority, opp.topic.substring(0, 65)); inserted++; }
    else { console.error('[ERR] P' + opp.priority, insRes.status, JSON.stringify(insRes.body).substring(0, 80)); errors++; }
  }
  console.log('Resume: inserted=' + inserted + ' skipped=' + skipped + ' errors=' + errors);
  const hp = OPPORTUNITIES.filter(o => o.priority <= 3).length;
  const cols = [...new Set(OPPORTUNITIES.map(o => o.suggested_collection))].length;
  await apiRequest('PATCH', '/rest/v1/agent_runs?id=eq.' + runId, { status: 'completed', completed_at: new Date().toISOString(), items_processed: inserted, items_errors: errors, metadata: { new_opportunities: inserted, skipped_existing: skipped, high_priority: hp, collections_covered: cols, total_analyzed: OPPORTUNITIES.length, run_date: new Date().toISOString().split('T')[0] } });
  console.log('TERMINE — Run ID:', runId);
}
main().catch(e => { console.error('FATAL:', e); process.exit(1); });
