name: Deploy to Hostinger

on:
  push:
    branches: [ production ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Astro site
      run: npm run astro:build
    
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy via SSH with debug
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        script: |
          echo "=== Cleaning target directory ==="
          ls -la ${{ secrets.REMOTE_PATH }}
          rm -rf ${{ secrets.REMOTE_PATH }}/*
          echo "=== Directory cleaned ==="
          ls -la ${{ secrets.REMOTE_PATH }}
    
    - name: Copy files via SCP with debug
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        source: "dist/*"
        target: ${{ secrets.REMOTE_PATH }}
        strip_components: 1
    
    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "=== Final directory structure ==="
          ls -la ${{ secrets.REMOTE_PATH }}
          echo "=== Checking partenaires ==="
          ls -la ${{ secrets.REMOTE_PATH }}/partenaires/ || echo "partenaires directory not found"
