name: Deploy to Hostinger

on:
  push:
    branches: [ production ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Astro site
      run: npm run astro:build
    
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
    
    - name: Build only (manual deployment required)
      run: |
        echo "=== Build completed successfully ==="
        echo "Files ready for manual deployment in 'dist' folder"
        echo "Use scripts/deploy-manual.ps1 for deployment instructions"
        echo ""
        echo "🎯 Page partenaires will be accessible at:"
        echo "https://glp1-france.fr/partenaires"
        echo ""
        echo "📊 Build summary:"
        ls -la dist/
        echo ""
        echo "✅ partenaires directory:"
        ls -la dist/partenaires/ || echo "partenaires page built as single file"
        
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: website-build
        path: dist/
        retention-days: 30
